appName: go_emqx_exhook
port: 16565

# Rocketmq、Rabbitmq、Kafka
mqType: Kafka

bridgeRule:
  topics:
    - "/#"

rocketmqConfig:
  nameServer:
    - 127.0.0.1:9876
  topic: emqx_exhook
  tag: exhook
  groupName: exhook
  retry: 2

rabbitmqConfig:
  addresses:
    - amqp://guest:guest@127.0.0.1
  virtualHost: /
  routingKeys: exhook
  exchangeName: emqx.exhook

kafkaConfig:
  addresses:
    - 127.0.0.1:9092
  topic: emqx_exhook

## 发送方式 queue or direct ，默认 queue
sendMethod: queue

queue:
  batchSize: 100
  workers: 2
  lingerTime: 1
