appName: go_emqx_exhook
port: 16565
mqType: Rocketmq

bridgeRule:
  sourceTopics:
    - "/#"
  targetTopic: hello_msg_exhook

rocketmqConfig:
  nameServer:
    - 192.168.0.188:9876
  targetTag: exhook
  groupName: exhook
  retry: 2

rocketmqConfig:
  nameServer:
    - 192.168.0.188:9876
  targetTag: exhook
  groupName: exhook
  retry: 2

## 发送方式 queue or direct ，默认 queue
sendMethod: queue

queue:
  batchSize: 100
  workers: 2
  lingerTime: 1
