# Rocketmq、Kafka、Rabbitmq、Redis
mqType: Redis


bridgeRule:
  topics:
    - "/#"


redisConfig:
  addresses:
    - 192.168.0.188:6379
  streamName: emqx_exhook
  db: 2
  #username: redis123
  #password: redis123456
  #masterName: mymaster
  #sentinelUsername: sentinel123456
  #sentinelPassword: sentinel123456
