# Rocketmq、Kafka、Rabbitmq、Redis
mqType: Kafka

bridgeRule:
  topics:
    - "/#"


# kafka 配置，需要提前创建 主题(emqx_exhook)
kafkaConfig:
  addresses:
    - mht01:9092
  topic: emqx_exhook
  sasl:
    enable: true
    user: admin
    password: admin123456
  tls:
    enable: true
    tlsSkipVerify: true
    caFile: /apps/server.cer.pem
    certFile: /apps/client.cer.pem
    keyFile: /apps/client.key.pem
