# Rocketmq、Kafka、Rabbitmq、RabbitmqStream、Redis
mqType: Kafka

bridgeRule:
  topics:
    - "/#"

# kafka 配置，需要提前创建 主题(emqx_exhook)
kafkaConfig:
  addresses:
    - kafka3:9092
  topic: emqx_exhook
  # 消息压缩类型 支持: "none", "gzip", "snappy", "lz4", "zstd", 默认: "none"
  compressionCodec: zstd
  # NumPartitions contains the number of partitions to create in the topic, or
  # -1 if we are either specifying a manual partition assignment or using the
  # default partitions.
  numPartitions: 1
  # ReplicationFactor contains the number of replicas to create for each
  # partition in the topic, or -1 if we are either specifying a manual
  # partition assignment or using the default replication factor.
  replicationFactor: 1
  # ConfigEntries contains the custom topic configurations to set.
  sasl:
    enable: true
    user: admin
    password: 123456
  configEntries:
    retention.ms: 604800000
