appName: go_emqx_exhook
port: 16565

# Rocketmq、Rabbitmq、Kafka
mqType: Rabbitmq

# emqx 主题
bridgeRule:
  topics:
    - "/#"

# rocketmq 配置，需要提前创建 主题(emqx_exhook)
rocketmqConfig:
  nameServer:
    - 192.168.0.188:9876
  topic: emqx_exhook
  tag: exhook
  groupName: exhook


# rabbitmq 配置，需要提前创建 队列(exhook_queue) 并且绑定 交换机(amq.direct)
rabbitmqConfig:
  addresses:
    - amqp://rabbit:mht123456@192.168.0.188:5672
  exchangeName: amq.direct
  routingKeys: exhook


# kafka 配置，需要提前创建 主题(emqx_exhook)
kafkaConfig:
  addresses:
    - 192.168.0.188:9092
  topic: emqx_exhook


# 发送方式 queue or direct ，默认 queue
# 注: rabbitmq 不支持队列发送
sendMethod: queue

queue:
  batchSize: 100
  workers: 2
  lingerTime: 1
