# Rocketmq、Kafka、Rabbitmq、RabbitmqStream、Redis
mqType: RabbitmqStream

bridgeRule:
  topics:
    - "/#"

rabbitmqStreamConfig:
  addresses:
    - rabbitmq-stream://rabbit:qlm123456@192.168.1.168:5552
  streamName: emqx_exhook
