# Rocketmq、Kafka、Rabbitmq、RabbitmqStream、Redis
mqType: RabbitmqStream

bridgeRule:
  topics:
    - "/#"


# rabbitmq 配置，需要提前创建 队列(exhook_queue) 并且绑定 交换机(amq.direct)
rabbitmqConfig:
  addresses:
    - amqp://rabbit:TE8qP3MZIksFzkSHZq@rabbitmq01:5671
    - amqp://rabbit:TE8qP3MZIksFzkSHZq@rabbitmq02:5672
    - amqp://rabbit:TE8qP3MZIksFzkSHZq@rabbitmq03:5673
  exchangeName: amq.direct
  routingKeys: emqx_exhook


# RabbitmqStream 配置 流 emqx_exhook
rabbitmqStreamConfig:
  addresses:
    - rabbitmq-stream://rabbit:TE8qP3MZIksFzkSHZq@rabbitmq01:5551
    - rabbitmq-stream://rabbit:TE8qP3MZIksFzkSHZq@rabbitmq02:5552
    - rabbitmq-stream://rabbit:TE8qP3MZIksFzkSHZq@rabbitmq03:5553
  streamName: emqx_exhook
  maxAge: 24h
  maxLengthBytes: 10gb
  maxSegmentSizeBytes: 1gb
  compressionCodec: zstd
