appName: go_emqx_exhook
port: 16565

bridgeRule:
  sourceTopics:
    - "/#"
  targetTopic: emqx_msg_bridge
  targetTag: emqx

rocketmqConfig:
  nameServer:
    - 192.168.0.188:9876

queue:
  batchSize: 100
  workers: 1
  lingerTime: 1
