appName: go_emqx_exhook
port: 16565

bridgeRule:
  sourceTopics:
    - "/#"
  targetTopic: hello_msg_exhook
  targetTag: emqx

rocketmqConfig:
  nameServer:
    - 192.168.0.188:9876

## 发送方式 queue or direct ，默认 queue
sendMethod: queue

queue:
  batchSize: 100
  workers: 2
  lingerTime: 1
