# Rocketmq、Kafka、Rabbitmq、Redis
mqType: Redis


bridgeRule:
  topics:
    - "/#"


redisConfig:
  addresses:
    - dev:6379
  streamName: emqx_exhook
  #streamMaxLen: 10
  db: 3
  #username: redis123
  password: qlm123456
  #masterName: mymaster
  #sentinelUsername: sentinel123456
  #sentinelPassword: sentinel123456
