version: '3'

networks:
  app-net1:
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

services:

  kafka3-sasl:
    image: bitnami/kafka:3.9.0-debian-12-r11
    container_name: kafka3
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://127.0.0.1:9092

      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=123456

      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=admin
      - KAFKA_CONTROLLER_PASSWORD=123456

      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=admin
      - KAFKA_INTER_BROKER_PASSWORD=123456
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
    deploy:
      resources:
        limits:
          memory: 1g



  kafka3-ssl:
    image: bitnami/kafka:3.9.0-debian-12-r11
    container_name: kafka3-ssl
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka3-ssl:9093
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://127.0.0.1:9092
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=admin123456
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=admin
      - KAFKA_CONTROLLER_PASSWORD=admin123456
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=admin
      - KAFKA_INTER_BROKER_PASSWORD=admin123456
      - KAFKA_CERTIFICATE_PASSWORD=kafka3
      - KAFKA_TLS_TYPE=JKS # JKS or PEM
    volumes:
      - $PWD/kafka3-ssl/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - $PWD/kafka3-ssl/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
    deploy:
      resources:
        limits:
          memory: 1g


  kafka3_emqx_exhook:
    image: thousmile/go_emqx_exhook:2.2
    container_name: kafka3_emqx_exhook
    ports:
      - "16565:16565"
    volumes:
      - ./kafka3-ssl/config.yaml:/apps/config.yaml
      - ./kafka3-ssl/truststore/server.cer.pem:/apps/server.cer.pem
      - ./kafka3-ssl/keystore/client.cer.pem:/apps/client.cer.pem
      - ./kafka3-ssl/keystore/client.key.pem:/apps/client.key.pem
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    extra_hosts:
      - mht01:172.21.0.8
    networks:
      app-net1:
    deploy:
      resources:
        limits:
          memory: 258m



  rabbitmq01:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq01
    hostname: rabbitmq01
    ports:
      - "5671:5672"
      - "5551:5552"
      - "15671:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit123
      - RABBITMQ_NODENAME=qlm@rabbitmq01
      - RABBITMQ_ERLANG_COOKIE=kuviC1Q6J4AWUHz3mQDIPTXiypbp3I5u
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    volumes:
      - ./rabbitmq01/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq01/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq01/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.21.0.11
    deploy:
      resources:
        limits:
          memory: 1g


  rabbitmq02:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq02
    hostname: rabbitmq02
    ports:
      - "5672:5672"
      - "5552:5552"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit123
      - RABBITMQ_NODENAME=qlm@rabbitmq02
      - RABBITMQ_ERLANG_COOKIE=kuviC1Q6J4AWUHz3mQDIPTXiypbp3I5u
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    volumes:
      - ./rabbitmq02/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq02/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq02/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.21.0.12
    deploy:
      resources:
        limits:
          memory: 1g


  rabbitmq03:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq03
    hostname: rabbitmq03
    ports:
      - "5673:5672"
      - "5553:5552"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit123
      - RABBITMQ_NODENAME=qlm@rabbitmq03
      - RABBITMQ_ERLANG_COOKIE=kuviC1Q6J4AWUHz3mQDIPTXiypbp3I5u
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    volumes:
      - ./rabbitmq03/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq03/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq03/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.21.0.13
    deploy:
      resources:
        limits:
          memory: 1g



  kafka0:
    image: bitnami/kafka:3.9.0-debian-12-r11
    container_name: kafka0
    hostname: kafka0
    ports:
      - "9091:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=XEAwssnk6wKmlsaaXsihxaaGYS4Z3Qnl
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    volumes:
      - /d/docker/kafka0/data:/bitnami/kafka/data
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.21.0.21
    deploy:
      resources:
        limits:
          memory: 1g


  kafka1:
    image: bitnami/kafka:3.9.0-debian-12-r11
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=XEAwssnk6wKmlsaaXsihxaaGYS4Z3Qnl
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    volumes:
      - /d/docker/kafka1/data:/bitnami/kafka/data
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.21.0.22
    deploy:
      resources:
        limits:
          memory: 1g


  kafka2:
    image: bitnami/kafka:3.9.0-debian-12-r11
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9093:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=XEAwssnk6wKmlsaaXsihxaaGYS4Z3Qnl
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    volumes:
      - /d/docker/kafka2/data:/bitnami/kafka/data
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.21.0.23
    deploy:
      resources:
        limits:
          memory: 1g

